# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 88897924dd8aad64f0e05a70fa84222cb0528c45ff85a3f1f9dc63f96a2686663f1b10764b8ca5edfb68b2abaec867f8218891efb33f0268119de93f716ee5bd

test:
  secret_key_base: 4ef8dd816dc8dfe2dd914706cd844eda5fd04cba373d5cd28db207abcd8fa1bfc4620e637b4ab5dde7decc8ed5e98d8217a7f7d32f6d44cfe07228335455c2c1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
